### PR TITLE
Spec 2.0

### PR DESCRIPTION
**Pull request by ndpete**
Major Spec revision to 2.0 adds deployables list and conversion script that can be run for the whole org or for one specific repo.

### CODE REVIEW

**Comment by brettbeatty** [comment]
How many of the properties need nested into a deployable?
- **`assignment_group`** How often are different assignment groups responsible for different items within a single repo?
- **`maintained_by`** I could potentially see a case where someone maintains only one deployable, but I'm not confident that's what we want from this field.
- **`developed_by_byu`** Are there cases where this wouldn't apply to the whole repo?
- **`ddd`** I don't know much about DDD, but hopefully your whole repo falls under the same domain.
- **`links`** `source_repo_url` is for sure the same, but I picture `swagger_urls` and `system_documentation_url` being the same as well.
- **`federation_json_url`** will be the same for the whole repo

**Comment by pauldeden** [comment]
<my opinion>federation_json_url should definitely be brought to the top level and not duplicated since we are in the same repo.  The others I can see cases, though hopefully rare, that they would be used separately per deployable.</my opinion>

What do you think @ndpete?

**Comment by pauldeden** [comment]
You two have 75% of the decision making power on this since you are coding it.  I have 25%.  Let me know what you decide.

**Comment by ndpete** [comment]
I agree with you opinion. I think there are potential cases where the others could be used differently and by its nature federation_json_url will be the same for all deployables.

What are your thoughts @brettbeatty

**Comment by pauldeden** [comment]
OK, the vote is to move source_repo_url to top scope and remove federation_json_url.

**Pull request closed without merging**
